# Dependabot Configuration for SerialPy
# See: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # ============================================================================
  # Python Dependencies (pyproject.toml) - Unified Configuration
  # ============================================================================

  # All Python Dependencies (Smart Update Strategy)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Etc/UTC"
    target-branch: "main"  # Changed to main branch
    open-pull-requests-limit: 8
    reviewers:
      - "danielendler"
    assignees:
      - "danielendler"
    commit-message:
      prefix: "deps"
      prefix-development: "dev-deps"
      include: "scope"
    # Conservative approach for ML libraries, aggressive for dev tools
    ignore:
      # Pin ML libraries that need careful version management
      - dependency-name: "torch"
        update-types: ["version-update:semver-major"]
      - dependency-name: "tensorflow"
        update-types: ["version-update:semver-major"]
      - dependency-name: "jax"
        update-types: ["version-update:semver-major"]
      - dependency-name: "scikit-learn"
        update-types: ["version-update:semver-major"]
      # Be conservative with core data science libraries
      - dependency-name: "pandas"
        update-types: ["version-update:semver-major"]
      - dependency-name: "numpy"
        update-types: ["version-update:semver-major"]
    labels:
      - "dependencies"
      - "automated"

  # ============================================================================
  # GitHub Actions Workflows
  # ============================================================================
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
      timezone: "Etc/UTC"
    target-branch: "main"
    open-pull-requests-limit: 3
    reviewers:
      - "danielendler"
    assignees:
      - "danielendler"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "ci/cd"
      - "github-actions"
      - "automated"
