# Dependabot Configuration for SerialPy
# See: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # ============================================================================
  # Python Dependencies (pyproject.toml)
  # ============================================================================

  # Core and Optional Dependencies (Conservative Updates)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
      timezone: "Etc/UTC"
    target-branch: "develop"
    open-pull-requests-limit: 3
    reviewers:
      - "danielmeierendler"
    assignees:
      - "danielmeierendler"
    commit-message:
      prefix: "deps"
      prefix-development: "dev-deps"
      include: "scope"
    # Only update these core and optional dependencies
    allow:
      - dependency-type: "production"
    ignore:
      # Pin ML libraries that need careful version management
      - dependency-name: "torch"
        update-types: ["version-update:semver-major"]
      - dependency-name: "tensorflow"
        update-types: ["version-update:semver-major"]
      - dependency-name: "jax"
        update-types: ["version-update:semver-major"]
    labels:
      - "dependencies"
      - "automated"

  # Development Dependencies (Aggressive Updates)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "Etc/UTC"
    target-branch: "develop"
    open-pull-requests-limit: 5
    reviewers:
      - "danielmeierendler"
    assignees:
      - "danielmeierendler"
    commit-message:
      prefix: "dev-deps"
      include: "scope"
    # Only update development dependencies
    allow:
      - dependency-type: "development"
    labels:
      - "dependencies"
      - "development"
      - "automated"

  # ============================================================================
  # GitHub Actions Workflows
  # ============================================================================
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
      timezone: "Etc/UTC"
    target-branch: "develop"
    open-pull-requests-limit: 3
    reviewers:
      - "danielmeierendler"
    assignees:
      - "danielmeierendler"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "ci/cd"
      - "github-actions"
      - "automated"

  # ============================================================================
  # Documentation Dependencies (MkDocs, etc.)
  # ============================================================================
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "tuesday"
      time: "09:00"
      timezone: "Etc/UTC"
    target-branch: "develop"
    open-pull-requests-limit: 2
    reviewers:
      - "danielmeierendler"
    assignees:
      - "danielmeierendler"
    commit-message:
      prefix: "docs"
      include: "scope"
    # Only documentation-related dependencies
    allow:
      - dependency-name: "mkdocs*"
      - dependency-name: "mkdocstrings*"
    labels:
      - "documentation"
      - "dependencies"
      - "automated"
