name: 📚 Documentation

on:
  push:
    branches: [main]
    paths: ['docs/**', 'mkdocs.yml', 'README.md']
  pull_request:
    branches: [main]
    paths: ['docs/**', 'mkdocs.yml', 'README.md']

jobs:
  # Build docs for preview/testing
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - name: 📥 Checkout
      uses: actions/checkout@v4

    - name: 🐍 Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: 📦 Install dependencies
      run: |
        pip install -e ".[docs]"

    - name: 🏗️ Build docs
      run: |
        mkdocs build --strict

    - name: 📤 Upload docs artifact
      uses: actions/upload-artifact@v4
      with:
        name: documentation
        path: site/

  # Deploy to GitHub Pages (backup)
  deploy-github-pages:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: build-docs
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
    - name: 📥 Checkout
      uses: actions/checkout@v4

    - name: 🐍 Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: 📦 Install dependencies
      run: |
        pip install -e ".[docs]"

    - name: 🏗️ Build docs
      run: |
        mkdocs build --strict

    - name: 🚀 Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
        cname: serialpy-docs.github.io  # Optional: custom domain
