name: 🏷️ Release Management

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., v0.1.2)'
        required: true
        type: string
      prerelease:
        description: 'Is this a pre-release?'
        required: false
        type: boolean
        default: false

jobs:
  validate-release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      is_prerelease: ${{ steps.version.outputs.is_prerelease }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: 📋 Extract version info
      id: version
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          VERSION="${{ github.event.inputs.version }}"
          IS_PRERELEASE="${{ github.event.inputs.prerelease }}"
        else
          VERSION="${GITHUB_REF#refs/tags/}"
          # Check if version contains alpha, beta, rc, dev
          if [[ "$VERSION" =~ (alpha|beta|rc|dev) ]]; then
            IS_PRERELEASE="true"
          else
            IS_PRERELEASE="false"
          fi
        fi

        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "is_prerelease=$IS_PRERELEASE" >> $GITHUB_OUTPUT

        echo "🏷️ Version: $VERSION"
        echo "🔄 Pre-release: $IS_PRERELEASE"

    - name: 🔍 Validate version format
      run: |
        VERSION="${{ steps.version.outputs.version }}"
        if [[ ! "$VERSION" =~ ^v[0-9]+\.[0-9]+\.[0-9]+ ]]; then
          echo "❌ Invalid version format: $VERSION"
          echo "Expected format: v1.2.3, v1.2.3-alpha.1, etc."
          exit 1
        fi
        echo "✅ Version format is valid"

  create-release:
    needs: validate-release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: 📝 Generate changelog
      id: changelog
      run: |
        VERSION="${{ needs.validate-release.outputs.version }}"

        # Get the previous tag
        PREV_TAG=$(git describe --tags --abbrev=0 HEAD~1 2>/dev/null || echo "")

        if [ -n "$PREV_TAG" ]; then
          echo "📋 Changes since $PREV_TAG:"
          CHANGELOG=$(git log --pretty=format:"- %s" $PREV_TAG..HEAD)
        else
          echo "📋 Initial release changes:"
          CHANGELOG=$(git log --pretty=format:"- %s")
        fi

        # Save changelog to file and output
        echo "$CHANGELOG" > changelog.md

        # Create multi-line output
        {
          echo "changelog<<EOF"
          echo "$CHANGELOG"
          echo "EOF"
        } >> $GITHUB_OUTPUT

    - name: 🏷️ Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ needs.validate-release.outputs.version }}
        name: Release ${{ needs.validate-release.outputs.version }}
        body: |
          ## 🎉 What's New in ${{ needs.validate-release.outputs.version }}

          ${{ steps.changelog.outputs.changelog }}

          ## 📦 Installation

          ```bash
          pip install serialpy==${{ needs.validate-release.outputs.version }}
          ```

          ## 🔗 Links
          - **📚 Documentation**: https://serialpy.readthedocs.io
          - **🐛 Issues**: https://github.com/danielendler/SerialPy/issues
          - **💬 Discussions**: https://github.com/danielendler/SerialPy/discussions

          ---

          **Full Changelog**: https://github.com/danielendler/SerialPy/compare/${{ github.event.repository.default_branch }}...${{ needs.validate-release.outputs.version }}
        prerelease: ${{ needs.validate-release.outputs.is_prerelease == 'true' }}
        generate_release_notes: true

    - name: 📢 Create release discussion
      if: needs.validate-release.outputs.is_prerelease == 'false'
      uses: actions/github-script@v7
      with:
        script: |
          const version = '${{ needs.validate-release.outputs.version }}';

          github.rest.teams.addOrUpdateRepoPermissionsInOrg({
            org: context.repo.owner,
            team_slug: 'maintainers',
            owner: context.repo.owner,
            repo: context.repo.repo,
            permission: 'admin'
          }).catch(() => {}); // Ignore if team doesn't exist

          // Create discussion for major releases
          if (!version.includes('patch')) {
            github.rest.discussions.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `🎉 SerialPy ${version} Released!`,
              body: `
              ## SerialPy ${version} is now available! 🚀

              ### Installation
              \`\`\`bash
              pip install --upgrade serialpy
              \`\`\`

              ### What do you think?
              - How are you using SerialPy?
              - Any feedback on the new features?
              - Ideas for future improvements?

              **📚 [View Release Notes](https://github.com/danielendler/SerialPy/releases/tag/${version})**
              `,
              category_id: 'announcements'
            }).catch(err => console.log('Could not create discussion:', err.message));
          }

  trigger-publish:
    needs: [validate-release, create-release]
    runs-on: ubuntu-latest

    steps:
    - name: 🚀 Trigger PyPI publish
      uses: actions/github-script@v7
      with:
        script: |
          // Trigger the existing publish workflow
          github.rest.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'publish.yml',
            ref: '${{ needs.validate-release.outputs.version }}'
          });
